# Generated by Django 3.0.2 on 2020-01-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailList',
            fields=[
                ('fullname', models.TextField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('descript', models.TextField()),
                ('email', models.CharField(max_length=64)),
                ('img', models.CharField(max_length=64)),
            ],
        ),
    ]
